# Generated by Django 5.1.4 on 2026-06-22 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('anomaly_type', models.CharField(max_length=60)),
                ('severity', models.CharField(max_length=30)),
                ('deviation_percent', models.DecimalField(decimal_places=2, max_digits=6)),
                ('estimated_loss_mwh', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(default='OPEN', max_length=30)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='PowerStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=160)),
                ('capacity_mw', models.DecimalField(decimal_places=2, max_digits=8)),
                ('panel_count', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AiAdvice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advice_text', models.TextField()),
                ('recommended_action', models.TextField()),
                ('priority', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('anomaly_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advices', to='monitoring.anomalyevent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PowerForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_time', models.DateTimeField()),
                ('predicted_power_mw', models.DecimalField(decimal_places=2, max_digits=8)),
                ('predicted_energy_mwh', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('forecast_model', models.CharField(default='PF-24H-RULE', max_length=80)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='monitoring.powerstation')),
            ],
            options={
                'ordering': ['forecast_time'],
            },
        ),
        migrations.AddField(
            model_name='anomalyevent',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='monitoring.powerstation'),
        ),
        migrations.CreateModel(
            name='SubArray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('capacity_mw', models.DecimalField(decimal_places=2, max_digits=8)),
                ('orientation', models.CharField(max_length=40)),
                ('tilt_angle', models.DecimalField(decimal_places=2, max_digits=5)),
                ('inverter_id', models.CharField(max_length=40)),
                ('status', models.CharField(default='NORMAL', max_length=40)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_arrays', to='monitoring.powerstation')),
            ],
        ),
        migrations.CreateModel(
            name='PowerActual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_time', models.DateTimeField()),
                ('actual_power_mw', models.DecimalField(decimal_places=2, max_digits=8)),
                ('energy_mwh', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('pr_value', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('data_source', models.CharField(default='SCADA_SIM', max_length=80)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actuals', to='monitoring.powerstation')),
                ('sub_array', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actuals', to='monitoring.subarray')),
            ],
            options={
                'ordering': ['record_time'],
            },
        ),
        migrations.AddField(
            model_name='anomalyevent',
            name='sub_array',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomalies', to='monitoring.subarray'),
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_time', models.DateTimeField()),
                ('weather_status', models.CharField(max_length=40)),
                ('ghi_wm2', models.PositiveIntegerField(default=0)),
                ('temperature_c', models.DecimalField(decimal_places=2, max_digits=5)),
                ('wind_speed_ms', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cloud_cover_percent', models.PositiveIntegerField(default=0)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_records', to='monitoring.powerstation')),
            ],
            options={
                'ordering': ['record_time'],
            },
        ),
    ]
